/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
package com.nccs.saurav.SIS.GUI;
import com.nccs.saurav.SIS.DAO.UserDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author dipesh
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangeUsernameAndPassword
     */
    public ChangePassword() {
        initComponents();
        setTitle("Change Password");
        setLocationRelativeTo(null);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmPasswordTxt = new javax.swing.JPasswordField();
        newPasswordTxt = new javax.swing.JPasswordField();
        oldPasswordTxt = new javax.swing.JPasswordField();
        usernametxt = new javax.swing.JTextField();
        changebttn = new javax.swing.JButton();
        cancelbttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username:");

        jLabel2.setText("Old Password:");

        jLabel3.setText("New Password:");

        jLabel4.setText("Confirm Password:");

        changebttn.setText("Change");
        changebttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebttnActionPerformed(evt);
            }
        });

        cancelbttn.setText("Cancel");
        cancelbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changebttn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(confirmPasswordTxt)
                        .addComponent(newPasswordTxt)
                        .addComponent(oldPasswordTxt)
                        .addComponent(usernametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addComponent(cancelbttn))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(oldPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(newPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changebttn)
                    .addComponent(cancelbttn))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelbttnActionPerformed

    private void changebttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebttnActionPerformed
        // TODO add your handling code here:
        String username = usernametxt.getText();
        String oldPassword = new String(oldPasswordTxt.getPassword());
        String newPassword = new String(newPasswordTxt.getPassword());
        String confirmPassword = new String(confirmPasswordTxt.getPassword());
        if (validation()) {
            if (newPassword.equals(confirmPassword)) {
                boolean isValid = new UserDAO().changePassword(username, oldPassword, newPassword);
                if (isValid) {
                    JOptionPane.showMessageDialog(null, "Password Changed");
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Username and Password Incorrect");
                    oldPasswordTxt.setText("");
                    newPasswordTxt.setText("");
                    confirmPasswordTxt.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "New Password and Confirm password doesn't match");
                oldPasswordTxt.setText("");
                newPasswordTxt.setText("");
                confirmPasswordTxt.setText("");
            }
        }
    }//GEN-LAST:event_changebttnActionPerformed
    public boolean validation() {
        if (usernametxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username cannot be empty!");
            return false;
        }
        if (new String(newPasswordTxt.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "New Password cannot be empty!");
            return false;
        }
        if (new String(oldPasswordTxt.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Old Password cannot be empty!");
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbttn;
    private javax.swing.JButton changebttn;
    private javax.swing.JPasswordField confirmPasswordTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField newPasswordTxt;
    private javax.swing.JPasswordField oldPasswordTxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables

}
